package agilor.distributed.storage.inter.thrift; /**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-9-28")
public class HandleErrorException extends TException implements org.apache.thrift.TBase<HandleErrorException, HandleErrorException._Fields>, java.io.Serializable, Cloneable, Comparable<HandleErrorException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HandleErrorException");

  private static final org.apache.thrift.protocol.TField HWND_FIELD_DESC = new org.apache.thrift.protocol.TField("hwnd", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HandleErrorExceptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HandleErrorExceptionTupleSchemeFactory());
  }

  public int hwnd; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HWND((short)1, "hwnd");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HWND
          return HWND;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HWND_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HWND, new org.apache.thrift.meta_data.FieldMetaData("hwnd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HandleErrorException.class, metaDataMap);
  }

  public HandleErrorException() {
  }

  public HandleErrorException(
    int hwnd)
  {
    this();
    this.hwnd = hwnd;
    setHwndIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HandleErrorException(HandleErrorException other) {
    __isset_bitfield = other.__isset_bitfield;
    this.hwnd = other.hwnd;
  }

  public HandleErrorException deepCopy() {
    return new HandleErrorException(this);
  }

  @Override
  public void clear() {
    setHwndIsSet(false);
    this.hwnd = 0;
  }

  public int getHwnd() {
    return this.hwnd;
  }

  public HandleErrorException setHwnd(int hwnd) {
    this.hwnd = hwnd;
    setHwndIsSet(true);
    return this;
  }

  public void unsetHwnd() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HWND_ISSET_ID);
  }

  /** Returns true if field hwnd is set (has been assigned a value) and false otherwise */
  public boolean isSetHwnd() {
    return EncodingUtils.testBit(__isset_bitfield, __HWND_ISSET_ID);
  }

  public void setHwndIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HWND_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HWND:
      if (value == null) {
        unsetHwnd();
      } else {
        setHwnd((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HWND:
      return Integer.valueOf(getHwnd());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HWND:
      return isSetHwnd();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HandleErrorException)
      return this.equals((HandleErrorException)that);
    return false;
  }

  public boolean equals(HandleErrorException that) {
    if (that == null)
      return false;

    boolean this_present_hwnd = true;
    boolean that_present_hwnd = true;
    if (this_present_hwnd || that_present_hwnd) {
      if (!(this_present_hwnd && that_present_hwnd))
        return false;
      if (this.hwnd != that.hwnd)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_hwnd = true;
    list.add(present_hwnd);
    if (present_hwnd)
      list.add(hwnd);

    return list.hashCode();
  }

  @Override
  public int compareTo(HandleErrorException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHwnd()).compareTo(other.isSetHwnd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHwnd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hwnd, other.hwnd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HandleErrorException(");
    boolean first = true;

    sb.append("hwnd:");
    sb.append(this.hwnd);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HandleErrorExceptionStandardSchemeFactory implements SchemeFactory {
    public HandleErrorExceptionStandardScheme getScheme() {
      return new HandleErrorExceptionStandardScheme();
    }
  }

  private static class HandleErrorExceptionStandardScheme extends StandardScheme<HandleErrorException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HandleErrorException struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HWND
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.hwnd = iprot.readI32();
              struct.setHwndIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HandleErrorException struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(HWND_FIELD_DESC);
      oprot.writeI32(struct.hwnd);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HandleErrorExceptionTupleSchemeFactory implements SchemeFactory {
    public HandleErrorExceptionTupleScheme getScheme() {
      return new HandleErrorExceptionTupleScheme();
    }
  }

  private static class HandleErrorExceptionTupleScheme extends TupleScheme<HandleErrorException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HandleErrorException struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetHwnd()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetHwnd()) {
        oprot.writeI32(struct.hwnd);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HandleErrorException struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.hwnd = iprot.readI32();
        struct.setHwndIsSet(true);
      }
    }
  }

}

