/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef inter_CONSTANTS_H
#define inter_CONSTANTS_H

#include "inter_types.h"



class interConstants {
 public:
  interConstants();

};

extern const interConstants g_inter_constants;



#endif
